spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
      authentication-database: ${MONGO_AUTH_DB}

server:
  port: ${PORT}

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}

logging:
  level:
    org.springframework.data.mongodb: DEBUG